require("dotenv").config();
const express = require("express");
const path = require("path");
const bodyParser = require("body-parser");
const http = require('http');
const mongoose = require("mongoose"); 
const cookieParser = require('cookie-parser');

const app = express(); 
const server = http.createServer(app);

const connectDatabase = require('./src/infrastructure/mongooseDb');

app.use(express.json());


app.set("view engine", "ejs");
app.set("views", path.join(__dirname, "frontend"));
app.use(cookieParser());

app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
app.use(express.static(path.join(__dirname, "frontend")));
app.use(express.static(path.join(__dirname, "frontend", "public")));
app.use(express.urlencoded({ extended: true }));

const permisosRoutes = require("./src/routes/permisos.routes");
const usuariosSistemaRoutes = require("./src/routes/usuariosSistema.routes");
const bitacoraRoutes = require("./src/routes/bitacora.routes");
const simulationsRoutes = require("./src/routes/simulations.routes");
const simulationsTeamsRoutes = require("./src/routes/simulationsTeams.routes");
const gruposRoutes = require("./src/routes/grupos.routes");
const gruposUsuariosRoutes = require("./src/routes/gruposUsuarios.routes");
const logsDeleteRoutes = require("./src/routes/logsDelete.routes");
const recoveriesRoutes = require("./src/routes/recoveries.routes");
const dMActivosFijosRoutes = require("./src/routes/dMActivosFijos.routes");
const dMActivosFijosInventarioRoutes = require("./src/routes/dMActivosFijosInventario.routes");
const dMClientesRoutes = require("./src/routes/dMClientes.routes");
const dMEmpleadosRoutes = require("./src/routes/dMEmpleados.routes");
const dMSalaryTabulatorRoutes = require("./src/routes/dMSalaryTabulator.routes");
const dMEventPipeRoutes = require("./src/routes/dMEventPipe.routes");
const dMGastosRoutes = require("./src/routes/dMGastos.routes");
const dMMateriaPrimaRoutes = require("./src/routes/dMMateriaPrima.routes");
const dMMateriaPrimaCategoriaRoutes = require("./src/routes/dMMateriaPrimaCategoria.routes");
const dMMateriaPrimaInventarioRoutes = require("./src/routes/dMMateriaPrimaInventario.routes");
const dMOrderHistoryRoutes = require("./src/routes/dMOrderHistory.routes");
const dMProductoFamiliaRoutes = require("./src/routes/dMProductoFamilia.routes");
const dMPaisesRoutes = require("./src/routes/dMPaises.routes");
const dMProductionLinePhasesRoutes = require("./src/routes/dMProductionLinePhases.routes");
const dMProductionLineTemplatesRoutes = require("./src/routes/dMProductionLineTemplates.routes");
const dMProveedoresRoutes = require("./src/routes/dMProveedores.routes");
const dMProveedoresMPRoutes = require("./src/routes/dMProveedoresMP.routes");
const dMTransporteRoutes = require("./src/routes/dMTransporte.routes");
const dMRegionesRoutes = require("./src/routes/dMRegiones.routes");
const sDMActivosFijosRoutes = require("./src/routes/sDMActivosFijos.routes");
const sDMActivosFijosInventarioRoutes = require("./src/routes/sDMActivosFijosInventario.routes");
const sDMClientesRoutes = require("./src/routes/sDMClientes.routes");
const sDMEmpleadosRoutes = require("./src/routes/sDMEmpleados.routes");
const sDMSalaryTabulatorRoutes = require("./src/routes/sDMSalaryTabulator.routes");
const sDMGastosRoutes = require("./src/routes/sDMGastos.routes");
const sDMMateriaPrimaInventarioRoutes = require("./src/routes/sDMMateriaPrimaInventario.routes");
const sDMProductionLinePhasesRoutes = require("./src/routes/sDMProductionLinePhases.routes");
const sDMProductionLineTemplatesRoutes = require("./src/routes/sDMProductionLineTemplates.routes");
const sDMProductoFamiliaRoutes = require("./src/routes/sDMProductoFamilia.routes");
const sDMProveedoresRoutes = require("./src/routes/sDMProveedores.routes");
const sDMProveedoresMPRoutes = require("./src/routes/sDMProveedoresMP.routes");
const sDMTransporteRoutes = require("./src/routes/sDMTransporte.routes");
const simulationsDeliveredRawMaterialRoutes = require("./src/routes/simulationsDeliveredRawMaterial.routes");
const simulationsOrdersPurchasingsRoutes = require("./src/routes/simulationsOrdersPurchasings.routes");
const simulationsOrdersSuppliersRoutes = require("./src/routes/simulationsOrdersSuppliers.routes");
const simulationsPurchasingRoutes = require("./src/routes/simulationsPurchasing.routes");
const simulationsEventPipeRoutes = require("./src/routes/simulationsEventPipe.routes");
const simulationsEventsRoutes = require("./src/routes/simulationsEvents.routes");
const simulationsInventoryRoutes = require("./src/routes/simulationsInventory.routes");
const simulationsLogsRoutes = require("./src/routes/simulationsLogs.routes");
const simulationsOrdersRoutes = require("./src/routes/simulationsOrders.routes");
const solicitudesUsuariosRoutes = require("./src/routes/solicitudesUsuarios.routes");
const tDActivatedProductionLineRoutes = require("./src/routes/tDActivatedProductionLine.routes");
const tDMActivosFijosInventarioRoutes = require("./src/routes/tDMActivosFijosInventario.routes");
const tDMEmployeesRoutes = require("./src/routes/tDMEmployees.routes");
const tDProductionLineRoutes = require("./src/routes/tDProductionLine.routes");
const tDProductoFamiliaRoutes = require("./src/routes/tDProductoFamilia.routes");
const tDSimulationFinancialLogRoutes = require("./src/routes/tDSimulationFinancialLog.routes");
const xlsRoutes = require("./src/routes/xls.routes")

app.use("/permisos", permisosRoutes);
app.use("/usuariosSistema", usuariosSistemaRoutes);
app.use("/bitacora", bitacoraRoutes);
app.use("/simulations", simulationsRoutes);
app.use("/simulationsTeams", simulationsTeamsRoutes);
app.use("/grupos", gruposRoutes);
app.use("/gruposUsuarios", gruposUsuariosRoutes);
app.use("/logsDelete", logsDeleteRoutes);
app.use("/recoveries", recoveriesRoutes);
app.use("/dMActivosFijos", dMActivosFijosRoutes);
app.use("/dMActivosFijosInventario", dMActivosFijosInventarioRoutes);
app.use("/dMClientes", dMClientesRoutes);
app.use("/dMEmpleados", dMEmpleadosRoutes);
app.use("/dMSalaryTabulator", dMSalaryTabulatorRoutes);
app.use("/dMEventPipe", dMEventPipeRoutes);
app.use("/dMGastos", dMGastosRoutes);
app.use("/dMMateriaPrima", dMMateriaPrimaRoutes);
app.use("/dMMateriaPrimaCategoria", dMMateriaPrimaCategoriaRoutes);
app.use("/dMMateriaPrimaInventario", dMMateriaPrimaInventarioRoutes);
app.use("/dMOrderHistory", dMOrderHistoryRoutes);
app.use("/dMProductoFamilia", dMProductoFamiliaRoutes);
app.use("/dMPaises", dMPaisesRoutes);
app.use("/dMProductionLinePhases", dMProductionLinePhasesRoutes);
app.use("/dMProductionLineTemplates", dMProductionLineTemplatesRoutes);
app.use("/dMProveedores", dMProveedoresRoutes);
app.use("/dMProveedoresMP", dMProveedoresMPRoutes);
app.use("/dMTransporte", dMTransporteRoutes);
app.use("/dMRegiones", dMRegionesRoutes);
app.use("/sDMActivosFijos", sDMActivosFijosRoutes);
app.use("/sDMActivosFijosInventario", sDMActivosFijosInventarioRoutes);
app.use("/sDMClientes", sDMClientesRoutes);
app.use("/sDMEmpleados", sDMEmpleadosRoutes);
app.use("/sDMSalaryTabulator", sDMSalaryTabulatorRoutes);
app.use("/sDMGastos", sDMGastosRoutes);
app.use("/sDMMateriaPrimaInventario", sDMMateriaPrimaInventarioRoutes);
app.use("/sDMProductionLinePhases", sDMProductionLinePhasesRoutes);
app.use("/sDMProductionLineTemplates", sDMProductionLineTemplatesRoutes);
app.use("/sDMProductoFamilia", sDMProductoFamiliaRoutes);
app.use("/sDMProveedores", sDMProveedoresRoutes);
app.use("/sDMProveedoresMP", sDMProveedoresMPRoutes);
app.use("/sDMTransporte", sDMTransporteRoutes);
app.use("/simulationsDeliveredRawMaterial", simulationsDeliveredRawMaterialRoutes);
app.use("/simulationsOrdersPurchasings", simulationsOrdersPurchasingsRoutes);
app.use("/simulationsOrdersSuppliers", simulationsOrdersSuppliersRoutes);
app.use("/simulationsPurchasing", simulationsPurchasingRoutes);
app.use("/simulationsEventPipe", simulationsEventPipeRoutes);
app.use("/simulationsEvents", simulationsEventsRoutes);
app.use("/simulationsInventory", simulationsInventoryRoutes);
app.use("/simulationsLogs", simulationsLogsRoutes);
app.use("/simulationsOrders", simulationsOrdersRoutes);
app.use("/solicitudesUsuarios", solicitudesUsuariosRoutes);
app.use("/tDActivatedProductionLine", tDActivatedProductionLineRoutes);
app.use("/tDMActivosFijosInventario", tDMActivosFijosInventarioRoutes);
app.use("/tDMEmployees", tDMEmployeesRoutes);
app.use("/tDProductionLine", tDProductionLineRoutes);
app.use("/tDProductoFamilia", tDProductoFamiliaRoutes);
app.use("/tDSimulationFinancialLog", tDSimulationFinancialLogRoutes);
app.use("/xls", xlsRoutes);

(async () => {
  await connectDatabase.connectDatabase();

  server.listen(process.env.PORT, () => {
    console.log(`Server running on http://localhost:${process.env.PORT}`);
  });
})();
