const express = require("express");
const router = express.Router();

const permisosRoutes = require("./permisos.routes");
const usuariosSistemaRoutes = require("./usuariosSistema.routes");
const bitacoraRoutes = require("./bitacora.routes");
const simulationsRoutes = require("./simulations.routes");
const simulationsTeamsRoutes = require("./simulationsTeams.routes");
const gruposRoutes = require("./grupos.routes");
const gruposUsuariosRoutes = require("./gruposUsuarios.routes");
const logsDeleteRoutes = require("./logsDelete.routes");
const recoveriesRoutes = require("./recoveries.routes");
const dMActivosFijosRoutes = require("./dMActivosFijos.routes");
const dMActivosFijosInventarioRoutes = require("./dMActivosFijosInventario.routes");
const dMClientesRoutes = require("./dMClientes.routes");
const dMEmpleadosRoutes = require("./dMEmpleados.routes");
const dMSalaryTabulatorRoutes = require("./dMSalaryTabulator.routes");
const dMEventPipeRoutes = require("./dMEventPipe.routes");
const dMGastosRoutes = require("./dMGastos.routes");
const dMMateriaPrimaRoutes = require("./dMMateriaPrima.routes");
const dMMateriaPrimaCategoriaRoutes = require("./dMMateriaPrimaCategoria.routes");
const dMMateriaPrimaInventarioRoutes = require("./dMMateriaPrimaInventario.routes");
const dMOrderHistoryRoutes = require("./dMOrderHistory.routes");
const dMProductoFamiliaRoutes = require("./dMProductoFamilia.routes");
const dMPaisesRoutes = require("./dMPaises.routes");
const dMProductionLinePhasesRoutes = require("./dMProductionLinePhases.routes");
const dMProductionLineTemplatesRoutes = require("./dMProductionLineTemplates.routes");
const dMProveedoresRoutes = require("./dMProveedores.routes");
const dMProveedoresMPRoutes = require("./dMProveedoresMP.routes");
const dMTransporteRoutes = require("./dMTransporte.routes");
const dMRegionesRoutes = require("./dMRegiones.routes");
const sDMActivosFijosRoutes = require("./sDMActivosFijos.routes");
const sDMActivosFijosInventarioRoutes = require("./sDMActivosFijosInventario.routes");
const sDMClientesRoutes = require("./sDMClientes.routes");
const sDMEmpleadosRoutes = require("./sDMEmpleados.routes");
const sDMSalaryTabulatorRoutes = require("./sDMSalaryTabulator.routes");
const sDMGastosRoutes = require("./sDMGastos.routes");
const sDMMateriaPrimaInventarioRoutes = require("./sDMMateriaPrimaInventario.routes");
const sDMProductionLinePhasesRoutes = require("./sDMProductionLinePhases.routes");
const sDMProductionLineTemplatesRoutes = require("./sDMProductionLineTemplates.routes");
const sDMProductoFamiliaRoutes = require("./sDMProductoFamilia.routes");
const sDMProveedoresRoutes = require("./sDMProveedores.routes");
const sDMProveedoresMPRoutes = require("./sDMProveedoresMP.routes");
const sDMTransporteRoutes = require("./sDMTransporte.routes");
const simulationsDeliveredRawMaterialRoutes = require("./simulationsDeliveredRawMaterial.routes");
const simulationsOrdersPurchasingsRoutes = require("./simulationsOrdersPurchasings.routes");
const simulationsOrdersSuppliersRoutes = require("./simulationsOrdersSuppliers.routes");
const simulationsPurchasingRoutes = require("./simulationsPurchasing.routes");
const simulationsEventPipeRoutes = require("./simulationsEventPipe.routes");
const simulationsEventsRoutes = require("./simulationsEvents.routes");
const simulationsInventoryRoutes = require("./simulationsInventory.routes");
const simulationsLogsRoutes = require("./simulationsLogs.routes");
const simulationsOrdersRoutes = require("./simulationsOrders.routes");
const solicitudesUsuariosRoutes = require("./solicitudesUsuarios.routes");
const tDActivatedProductionLineRoutes = require("./tDActivatedProductionLine.routes");
const tDMActivosFijosInventarioRoutes = require("./tDMActivosFijosInventario.routes");
const tDMEmployeesRoutes = require("./tDMEmployees.routes");
const tDProductionLineRoutes = require("./tDProductionLine.routes");
const tDProductoFamiliaRoutes = require("./tDProductoFamilia.routes");
const tDSimulationFinancialLogRoutes = require("./tDSimulationFinancialLog.routes");

router.use("/permisos", permisosRoutes);
router.use("/usuarios-sistema", usuariosSistemaRoutes);
router.use("/bitacora", bitacoraRoutes);
router.use("/simulations", simulationsRoutes);
router.use("/simulations-teams", simulationsTeamsRoutes);
router.use("/grupos", gruposRoutes);
router.use("/grupos-usuarios", gruposUsuariosRoutes);
router.use("/logs-delete", logsDeleteRoutes);
router.use("/recoveries", recoveriesRoutes);
router.use("/dm-activos-fijos", dMActivosFijosRoutes);
router.use("/dm-activos-fijos-inventario", dMActivosFijosInventarioRoutes);
router.use("/dm-clientes", dMClientesRoutes);
router.use("/dm-empleados", dMEmpleadosRoutes);
router.use("/dm-salary-tabulator", dMSalaryTabulatorRoutes);
router.use("/dm-event-pipe", dMEventPipeRoutes);
router.use("/dm-gastos", dMGastosRoutes);
router.use("/dm-materia-prima", dMMateriaPrimaRoutes);
router.use("/dm-materia-prima-categoria", dMMateriaPrimaCategoriaRoutes);
router.use("/dm-materia-prima-inventario", dMMateriaPrimaInventarioRoutes);
router.use("/dm-order-history", dMOrderHistoryRoutes);
router.use("/dm-producto-familia", dMProductoFamiliaRoutes);
router.use("/dm-paises", dMPaisesRoutes);
router.use("/dm-production-line-phases", dMProductionLinePhasesRoutes);
router.use("/dm-production-line-templates", dMProductionLineTemplatesRoutes);
router.use("/dm-proveedores", dMProveedoresRoutes);
router.use("/dm-proveedores-mp", dMProveedoresMPRoutes);
router.use("/dm-transporte", dMTransporteRoutes);
router.use("/dm-regiones", dMRegionesRoutes);
router.use("/sdm-activos-fijos", sDMActivosFijosRoutes);
router.use("/sdm-activos-fijos-inventario", sDMActivosFijosInventarioRoutes);
router.use("/sdm-clientes", sDMClientesRoutes);
router.use("/sdm-empleados", sDMEmpleadosRoutes);
router.use("/sdm-salary-tabulator", sDMSalaryTabulatorRoutes);
router.use("/sdm-gastos", sDMGastosRoutes);
router.use("/sdm-materia-prima-inventario", sDMMateriaPrimaInventarioRoutes);
router.use("/sdm-production-line-phases", sDMProductionLinePhasesRoutes);
router.use("/sdm-production-line-templates", sDMProductionLineTemplatesRoutes);
router.use("/sdm-producto-familia", sDMProductoFamiliaRoutes);
router.use("/sdm-proveedores", sDMProveedoresRoutes);
router.use("/sdm-proveedores-mp", sDMProveedoresMPRoutes);
router.use("/sdm-transporte", sDMTransporteRoutes);
router.use("/simulations-delivered-raw-material", simulationsDeliveredRawMaterialRoutes);
router.use("/simulations-orders-purchasings", simulationsOrdersPurchasingsRoutes);
router.use("/simulations-orders-suppliers", simulationsOrdersSuppliersRoutes);
router.use("/simulations-purchasing", simulationsPurchasingRoutes);
router.use("/simulations-event-pipe", simulationsEventPipeRoutes);
router.use("/simulations-events", simulationsEventsRoutes);
router.use("/simulations-inventory", simulationsInventoryRoutes);
router.use("/simulations-logs", simulationsLogsRoutes);
router.use("/simulations-orders", simulationsOrdersRoutes);
router.use("/solicitudes-usuarios", solicitudesUsuariosRoutes);
router.use("/td-activated-production-line", tDActivatedProductionLineRoutes);
router.use("/tdm-activos-fijos-inventario", tDMActivosFijosInventarioRoutes);
router.use("/tdm-employees", tDMEmployeesRoutes);
router.use("/td-production-line", tDProductionLineRoutes);
router.use("/td-producto-familia", tDProductoFamiliaRoutes);
router.use("/td-simulation-financial-log", tDSimulationFinancialLogRoutes);

module.exports = router;
